OSC/ood-myjobs

- Gemfile.lock
- app/models/resource_mgr_adapter.rb
Fixes #172 
* Updates ood_job version
* Updates status handler
> New ood job

- app/assets/javascripts/workflows.js.coffee
- app/views/workflows/new.html.erb
Fixes a bug #177 where the template information would disappear on moving away and back to the window.
> Fix template reload bug

- app/assets/stylesheets/joyride.css
> Fixes #180 gradient precompile warning

- example_templates/default/main_job.sh
* Update default template to include bash header
> Add shebang to default for slurm support

- .gitignore
* Remove submodule entry
* git ignore templates folder
> Remove templates submodule entry

- example_templates/default/main_job.sh
> Simpler Default Template

- app/views/layouts/application.html.erb
> Remove copyright from footer

- app/assets/javascripts/workflows.js.coffee
- app/views/workflows/new.html.erb
> Remove invisible cluster

- app/models/template.rb
> Allow for relative paths in template creation

- app/controllers/workflows_controller.rb
- app/models/workflow.rb
- app/views/workflows/_new_from_path_form.html.erb
- app/views/workflows/index.html.erb
- app/views/workflows/new.html.erb
- app/views/workflows/new_from_path.html.erb
- config/routes.rb
Resolves #203 
* Converts New Workflow options into a dropdown
* Adds new routes and views for creating a new workflow from a source path
* If a manifest is found in the path, it sets the default name, host, account, and script.
* User can enter values in the view that override manifest defaults.
> Add ability to copy template from specified path

- CHANGELOG.md
- app/views/templates/_form.html.erb
> Redirect user to new templates page on cancel

- CHANGELOG.md
- app/assets/javascripts/workflows.js.coffee
- app/assets/stylesheets/workflows.css.scss
- app/helpers/pages_helper.rb
- app/models/workflow.rb
- app/views/workflows/index.html.erb
- app/views/workflows/show.json.jbuilder
Resolves #222 
* Display a cluster's metadata title instead of titlized id.
> Add a view helper to display the cluster title instead of the titleized id

- CHANGELOG.md
- README.md
release notes:
```
- Support for PBS Pro and basic support for LSF 9.1 via update to ood_core gem
```
> bump minor version

- CHANGELOG.md
- app/models/workflow.rb
> Sanitizes user input for account string

- CHANGELOG.md
- README.md
- app/views/layouts/application.html.erb
- app/views/workflows/index.html.erb
- manifest.yml
Not a perfect name, but better than "My Jobs". Also fixed Help Joyride tips for New button.
> Rename app to "Job Composer"

- CHANGELOG.md
- app/assets/javascripts/application.js
- app/assets/javascripts/workflows.js.coffee
- app/assets/stylesheets/application.css.scss
- app/views/workflows/index.html.erb
Disables all buttons and adds a "loading" indicator between job selections.
> Fix #226 Add loading notice

- app/assets/javascripts/workflows.js.coffee
- app/controllers/workflows_controller.rb
- app/views/workflows/index.html.erb
- app/views/workflows/new.html.erb
- config/initializers/open3_extensions.rb
- config/routes.rb
- add logging
- change copy_workflow to post method
-  Set the text field as being not-editable.
close #266 #249 #264
> Add logging

- config/environments/development.rb
- config/initializers/silence_eager_load_warnings.rb
> Disable the eager load warning

- app/views/workflows/_edit_form_job_attrs.html.erb
> Add placeholder text for job array spec

- app/views/workflows/new.html.erb
> Changed Edit Files to View Files

- app/controllers/application_controller.rb
- app/views/workflows/_edit_form.html.erb
- app/views/workflows/_edit_form_job_attrs.html.erb
- app/views/workflows/edit.html.erb
- config/configuration_singleton.rb
- config/initializers/locales.rb
- config/locales/en.yml
> Job options translations
